apiVersion: batch/v1
kind: Job
metadata:
  name: ulovdomov-tests
  namespace: default
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: ulovdomov-tests
          image: ulovdomov-tests:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ulovdomov-secrets
                  key: BASE_URL
            - name: TEST_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ulovdomov-secrets
                  key: TEST_USER_EMAIL
            - name: TEST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ulovdomov-secrets
                  key: TEST_USER_PASSWORD
      restartPolicy: Never
